function setData() {
  Process(
    "models.hero.Insert",
    [
      "avatar",
      "name",
      "alias",
      "title",
      "roles",
      "position",
      "attack",
      "defense",
      "magic",
      "difficulty",
      "gold_price",
      "coupon_price",
    ],
    [
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Annie.png"],
        "黑暗之女",
        "Annie",
        "安妮",
        ["mage"],
        ["中单"],
        2,
        3,
        10,
        6,
        4800,
        2000,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Olaf.png"],
        "狂战士",
        "Olaf",
        "奥拉夫",
        ["fighter", "tank"],
        ["上单", "打野"],
        9,
        5,
        3,
        3,
        1350,
        1500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Hecarim.png"],
        "战争之影",
        "Hecarim",
        "赫卡里姆",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Tryndamere.png"],
        "蟒王",
        "Hecarim",
        "蟒王",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/MonkeyKing.png"],
        "猴子",
        "猴子",
        "猴子",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Kayle.png"],
        "天使",
        "天使",
        "天使",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Sylas.png"],
        "塞拉斯",
        "塞拉斯",
        "塞拉斯",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Jinx.png"],
        "暴走萝莉",
        "Hecarim",
        "暴走萝莉",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Caitlyn.png"],
        "卡瑟琳",
        "Hecarim",
        "卡瑟琳",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Ezreal.png"],
        "探险家",
        "Hecarim",
        "探险家",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Jayce.png"],
        "未来守护者",
        "Hecarim",
        "未来守护者",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Lucian.png"],
        "卢锡安",
        "Hecarim",
        "卢锡安",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Vex.png"],
        "薇古丝",
        "Hecarim",
        "薇古丝",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Karthus.png"],
        "死歌",
        "Hecarim",
        "死歌",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Lux.png"],
        "拉克丝",
        "Hecarim",
        "拉克丝",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/MasterYi.png"],
        "剑圣",
        "Hecarim",
        "剑圣",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Maokai.png"],
        "树",
        "Hecarim",
        "树",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Fiora.png"],
        "剑姬",
        "Hecarim",
        "剑姬",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Xayah.png"],
        "逆羽",
        "Hecarim",
        "逆羽",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Varus.png"],
        "惩戒之箭",
        "Hecarim",
        "惩戒之箭",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Ryze.png"],
        "瑞兹",
        "Hecarim",
        "瑞兹",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Khazix.png"],
        "螳螂",
        "Hecarim",
        "螳螂",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
      [
        ["https://game.gtimg.cn/images/lol/act/img/champion/Blitzcrank.png"],
        "机器人",
        "Hecarim",
        "机器人",
        ["fighter", "tank"],
        ["上单", "打野"],
        8,
        6,
        4,
        6,
        4800,
        3500,
      ],
    ]
  );

  Process(
    "models.role.Insert",
    ["name", "type"],
    [
      ["法师", "mage"],
      ["战士", "fighter"],
      ["坦克", "tank"],
      ["辅助1", "support"],
      ["辅助2", "support"],
      ["辅助3", "support"],
      ["辅助4", "support"],
      ["辅助5", "support"],
      ["辅助6", "support"],
      ["辅助7", "support"],
      ["辅助8", "support"],
      ["辅助9", "support"],
      ["辅助10", "support"],

      ["辅助11", "support"],
      ["辅助12", "support"],
      ["辅助13", "support"],
      ["辅助14", "support"],
      ["辅助15", "support"],
      ["辅助16", "support"],
      ["辅助17", "support"],
      ["辅助18", "support"],
      ["辅助19", "support"],
      ["辅助120", "support"],
    ]
  );
}
